Base of RMI with User.md
alopesmendes/Rest pull request #3
Opened 2020-11-21 14:53 UTC by alopesmendes

Almost finish the base of rmi still need some changes.
Started writing the user readme on explain the usage.

2020-11-21 16:14 UTC, Alex1304 requested changes
Il y a certains choix de design qui peuvent vraiment être revus, sinon c'est un bon début.

En particulier:
* Revoir de quel côté (client ou serveur) doivent se situer les implémentations des interfaces RMI. Je vois que tu as dupliqué les implémentations de Car, de Rating et de Storage dans les deux projets et ça c'est pas bon. Seules les interfaces sont copiées-collées entre le client et le serveur, l'implémentation ne doit être que d'un seul côté (en l’occurrence celui qui fait le `new`). Pour Storage ce sera à priori le serveur, idem pour Car car le client ne fait que les récupérer par modèle. Pour Rating en revanche ce serait côté client, le serveur ne fait que lire les ratings que les clients lui donnent.
* Revoir l'implémentation de RatingService en utilisant correctement le pattern Observer au lieu d'utiliser des blocking queues
* Revoir l'utilité ou non de mettre certaines classes en Remote, par exemple je vois pas pourquoi Rating ou Employee devraient être remotes (je ne sais même pas à quoi sert Employee, on pourrait simplement passer les IDs pour les employés ou faire des passages par valeur pour Rating. Faut voir ce qui justifie ces choix).

Faudra sûrement modifier certaines choses dans l'UML aussi pour pouvoir s'y retrouver.

2020-11-21 16:14 UTC, Alex1304 commented on ifs-cars-server/src/main/java/fr/uge/corp/ifscars/cars/ICar.java
> +			return null;
Fais plutôt `throw new RuntimeException(e);` dans le catch au lieu de print et retourner `null`

2020-11-21 16:14 UTC, Alex1304 commented on ifs-cars-server/src/main/java/fr/uge/corp/ifscars/cars/Car.java
>  @SuppressWarnings("serial")
je pense c'est mieux d'enlever les `@SuppressWarnings("serial")` et de configurer Eclipse pour ignorer les warnings à la place. Quand on compile à la main (avec javac ou mvn compile) ces warnings n'existent pas.

2020-11-21 16:14 UTC, Alex1304 commented on ifs-cars-server/src/main/java/fr/uge/corp/ifscars/cars/ICar.java
> +	static class NullCar extends UnicastRemoteObject implements ICar {
Hmm, vu l'utilisation que tu fais du `NullCar` je ne vois pas trop ce qui justifie d'avoir ça. Il n'y avait pas moyen d'utiliser `java.util.Optional` à la place? Ça aurait été plus propre.

2020-11-21 16:14 UTC, Alex1304 commented on ifs-cars-server/src/main/java/fr/uge/corp/ifscars/renting/RentingService.java
> +	}
Alors bon peut être qu'à première vue ça marche, mais sauf que là on contourne le problème et au final on n'utilise même pas le pattern Observer... Bloquer le serveur avec des queues bloquantes est une très mauvaise idée (et une Map de Queue ça consomme de la mémoire...).

Si on réfléchit à la bonne manière de faire, il faut se rappeler du schéma:
client  ==> serveur : envoi d'une notification pour demander la location d'un modèle
client <== serveur : envoi d'une notification pour donner le véhicule au client une fois dispo
client ==> serveur : envoi d'une notification pour rendre le véhicule, avec le rating et la condition

On voit bien que les échanges de notifications se font dans les deux sens. On pourrait représenter un échange par une méthode dans la classe de celui qui reçoit la notification:
```java
// Lors de la location
server.receiveCarRentingRequest(client, model);
// le code de cette méthode appelle client.receiveCar(car) si disponible
// immédiatement, sinon ajoute le client en liste d'attente et sera traîté plus
// tard par receiveCarReturnRequest.

// Lors de la restitution
server.receiveCarReturnRequest(client, car, rating);
// le code de cette méthode appelle client.receiveCar(car) si un client est
// en attente pour ce modèle, sinon ne fait rien mis à part sauvegarder le rating
```
L'idéal serait de mettre l'appel à `client.receiveCar` dans une méthode privée `processQueue` qui est appelée à la fois dans `server.receiveCarRentingRequest` et dans `server.receiveCarReturnRequest`.

Avec ça, pas besoin de créer bêtement des interfaces IObserve et IObservateur pour au final ne pas les utiliser correctement.

2020-11-21 16:14 UTC, Alex1304 commented on renting-app/src/main/java/fr/uge/corp/rentingapp/employee/IEmployee.java
> +public interface IEmployee {
T'as oublié le `extends Remote`

2020-11-22 16:50 UTC, alopesmendes commented on ifs-cars-server/src/main/java/fr/uge/corp/ifscars/renting/RentingService.java
> +	}
J'ai implemente les differentes methodes. Les dfferents à noter sont que pour la queue j'ai decide de plutot sauvergarder les temps des demande avec System.currentTime. J'ai vire les classes donc il a seulement les interfaces. ICar il extends toujours Remote puisque j'avais besoin du cote client pour retourne la voiture. J'ai update le readme aussi

2020-11-22 22:12 UTC, Alex1304 commented
Ok merci on va voir plus tard ce qui peut être encore amélioré, pour l'instant c'est ok

2020-11-22 22:12 UTC, merged